Repository AdoptOpenJDK/openjdk-api-v3, pull requests merged in 2020-08, with the labels that each got.

#267 Refactor to decouple AdoptBinaryMapper and CachedGithubHtmlClient
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/BinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
Labels: enhancement

#266 Refactor GitHubAuth to prevent local configuration from causing test failures or harmful logging
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GitHubAuth.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GitHubAuthTest.kt
Labels: bug

#271 Merge staging into master
  .s2i/bin/assemble
  adoptopenjdk-api-v3-frontend/pom.xml
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsInterceptor.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsTelemetery.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/V1Route.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/resources/ApplicationInsights.xml
  adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/TestRunner.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V3Test.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Asset.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Installer.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Package.kt
  adoptopenjdk-api-v3-persistance/pom.xml
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt
  adoptopenjdk-api-v3-persistance/src/test/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClientTest.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/BinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoAPIPersistenceTests.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt
  pom.xml
Labels: enhancement

#274 Sync staging with master
  .dockerignore
  CONTRIBUTING.md
  Dockerfile
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GitHubAuth.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GitHubAuthTest.kt
  docker-compose.yml
  docs/STRUCTURE.md
  docs/adoptopenjdk-api-architecture-container.svg
  docs/adoptopenjdk-api-architecture-context.svg
Labels: enhancement

#276 Add support for ADRs within the project structure
  .adr-dir
  CONTRIBUTING.md
  docs/adr/0001-record-architecture-decisions.md
Labels: documentation, enhancement
