Repository AdoptOpenJDK/openjdk-api-v3, pull requests merged in 2020-03, with the labels that each got.

#125 Bring #124, #114 and #111 from staging into master
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
  adoptopenjdk-api-v3-updater/src/main/resources/logback.xml
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
Labels: enhancement

#126 add health check script
  .s2i/bin/assemble
  scripts/healthCheck.sh
Labels: enhancement

#127 Bring health check from staging into master
  .s2i/bin/assemble
  scripts/healthCheck.sh
Labels: enhancement

#130 Add support for debug images
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ImageType.kt
Labels: enhancement

#131 add description to top of swagger doc
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
Labels: documentation

#133 Keep bad stats in staging instance so we can diagnose reporting issues
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
Labels: enhancement

#136 Split releases with a mix of versions, resolving #120
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/FeatureRelease.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/GithubId.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GitHubApi.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/GraphQLGitHubClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequestInterface.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHRelease.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GithubIdDeserializer.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/summary/GHReleaseSummary.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamReleaseMapperTest.kt
Labels: bug

#137 Prevent double counting stats when splitting releases
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
Labels: bug
