Repository AdoptOpenJDK/openjdk-api-v3, pull requests merged in 2020-05, with the labels that each got.

#197 Overhaul of Maven files + initial CONTRIBUTING.md
  CONTRIBUTING.md
  adoptopenjdk-api-v3-frontend/pom.xml
  adoptopenjdk-api-v3-updater/pom.xml
  gradle/wrapper/gradle-wrapper.properties
  pom.xml
Labels: enhancement

#175 Add daily jvmImpl download counts to stats updater
  .gitignore
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStatsDbEntry.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/GithubDownloadStatsDbEntry.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
Labels: enhancement

#201 Initial project stucture doc
  docs/STRUCTURE.md
Labels: enhancement

#200 Update contributing + some minor fixes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  CONTRIBUTING.md
  adoptopenjdk-api-v3-models/pom.xml
  adoptopenjdk-api-v3-updater/pom.xml
  gradle/wrapper/gradle-wrapper.properties
  pom.xml
Labels: enhancement

#202 Add setup details to documentation
  CONTRIBUTING.md
Labels: documentation

#203 New monthly endpoint and adding jvmImpl filter
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/MonthlyStatsPathTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/MonthlyDownloadDiff.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
Labels: enhancement

#211 Possible solution to #209 on staging
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
Labels: bug

#207 add LinuxLH, fixes #204
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/HeapSize.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
Labels: bug

#198 Release installer paths from staging
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt
Labels: enhancement

#205 Fix `page_size` parameter in AssetsResource and ReleaseListResource
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseNamesPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionPathTest.kt
Labels: bug
