Repository AdoptOpenJDK/openjdk-api-v3, pull requests merged in 2020-07, with the labels that each got.

#233 Added link to structure.md
  adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html
Labels: documentation

#234 Take staging live
  adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
Labels: enhancement

#240 Fix link to STRUCTURE.md doc
  CONTRIBUTING.md
Labels: bug, documentation

#239 Explicitly set serverSelectionTimeoutMS for 'fallback' Mongo connection string
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
Labels: enhancement

#246 allow caller to set sort method
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortMethod.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
Labels: enhancement

#241 Merge master into staging
  CONTRIBUTING.md
  README.md
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortMethod.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
  docs/STRUCTURE.md
Labels: enhancement

#252 Fix packaging
  .s2i/bin/assemble
Labels: bug

#253 Rework sampling to track full request time
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsInterceptor.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsTelemetery.kt
  adoptopenjdk-api-v3-frontend/src/main/resources/ApplicationInsights.xml
Labels: bug

#257 Prevent failed build from passing
  .s2i/bin/assemble
Labels: bug

#258 Build & run the API stack locally with docker
  .dockerignore
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yml
Labels: enhancement

#259 print update stats for debugging
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
Labels: enhancement

#261 Add update time to db and poll updates more frequently
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/TestRunner.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoAPIPersistenceTests.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt
Labels: enhancement

#262 Fix npe
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
Labels: bug

#263 Stream checksum digest to try to avoid running out of memory
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt
Labels: bug

#260 Expose metadata_link for binary assets
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Asset.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Installer.kt
  adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Package.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
Labels: enhancement

#264 Prevent updater from scheduling updates
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V3Test.kt
  adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
  adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt
Labels: bug
