Repository AdoptOpenJDK/openjdk-api-v3, pull requests merged in 2021-06, with the labels that each got.

#405 Reduce the amount of test data generated
  adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
Labels: enhancement

#414 Fix setting the correct vendor on temurin repo
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
  adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
Labels: bug

#407 Code of Conduct for contributors #291
  CODE_OF_CONDUCTION.md
Labels: documentation

#418 Merge in latest from adoptium
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsPathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/FrontendTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
  adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
  adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
  pom.xml
Labels: enhancement

#421 Use correct mapper for adoptopenjdk
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
Labels: bug

#426 Minor rest assured updates
  .gitignore
  adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
  pom.xml
Labels: dependencies, enhancement
